import 'bootstrap/dist/css/bootstrap.css'
import { Inter } from "next/font/google";
import "./globals.css";
import { CurrencyProvider } from '../app/CurrencyContext'; // Adjust the path as needed


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "International Gift",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressContentEditableWarning
        suppressHydrationWarning 
        className={inter.className}>
        <CurrencyProvider>{children}</CurrencyProvider>
        
        </body>
    </html>
  );
}
